#define isrollback Visrollback
#define islogopen Vislogopen
#define isaddindex Visaddindex
#define isaudit Visaudit
#define isdelcurr Visdelcurr
#define iserase Viserase
#define isrecover Visrecover
#define isbegin Visbegin
#define isunlock Visunlock
#define islogclose Vislogclose
#define isrewcurr Visrewcurr
#define isstart Visstart
#define isdelrec Visdelrec
#define isdelete Visdelete
#define isrewrec Visrewrec
#define isdelindex Visdelindex
#define isrewrite Visrewrite
#define iscleanup Viscleanup
#define iscommit Viscommit
#define isuniqueid Visuniqueid
#define isindexinfo Visindexinfo
#define iswrcurr Viswrcurr
#define isopen Visopen
#define iscluster Viscluster
#define isflush Visflush
#define isbuild Visbuild
#define isrelease Visrelease
#define iswrite Viswrite
#define islock Vislock
#define isread Visread
#define isrename Visrename
#define isclose Visclose
#define issetunique Vissetunique
#define ldint Vldint
#define ldlong Vldlong
#define lddblnull Vlddblnull
#define ldfltnull Vldfltnull
#define ldfloat Vldfloat
#define ldchar Vldchar
#define lddecimal Vlddecimal
#define lddbl Vlddbl
#define stchar Vstchar
#define stfloat Vstfloat
#define stdecimal Vstdecimal
#define stfltnull Vstfltnull
#define stdblnull Vstdblnull
#define stint Vstint
#define stlong Vstlong
#define stdbl Vstdbl
#define deccvdbl Vdeccvdbl
#define deccopy Vdeccopy
#define deccvint Vdeccvint
#define dectoflt Vdectoflt
#define decdiv Vdecdiv
#define deccvlong Vdeccvlong
#define dectolong Vdectolong
#define dectoasc Vdectoasc
#define dececvt Vdececvt
#define dectodbl Vdectodbl
#define decsub Vdecsub
#define decadd Vdecadd
#define decmul Vdecmul
#define deccvasc Vdeccvasc
#define decfcvt Vdecfcvt
#define deccmp Vdeccmp
#define deccvflt Vdeccvflt
#define dectoint Vdectoint
